import { v7 as uuidv7 } from 'uuid'

import { contact } from '@/db/schemas/contacts'
import { db } from '@/db'

// Sample data arrays for generating realistic contacts
const firstNames = [
  'James',
  'Mary',
  'John',
  'Patricia',
  'Robert',
  'Jennifer',
  'Michael',
  'Linda',
  'William',
  'Barbara',
  'David',
  'Elizabeth',
  'Richard',
  'Susan',
  'Joseph',
  'Jessica',
  'Thomas',
  'Sarah',
  'Christopher',
  'Karen',
  'Charles',
  'Nancy',
  'Daniel',
  'Lisa',
  'Matthew',
  'Betty',
  'Anthony',
  'Margaret',
  'Mark',
  'Sandra',
  'Donald',
  'Ashley',
  'Steven',
  'Kimberly',
  'Paul',
  'Emily',
  'Andrew',
  'Donna',
  'Joshua',
  'Michelle',
  'Kenneth',
  'Carol',
  'Kevin',
  'Amanda',
  'Brian',
  'Dorothy',
  'George',
  'Melissa',
  'Timothy',
  'Deborah',
  'Ronald',
  'Stephanie',
  'Edward',
  'Rebecca',
  'Jason',
  'Sharon',
  'Jeffrey',
  'Laura',
  'Ryan',
  'Cynthia',
  'Jacob',
  'Kathleen',
  'Gary',
  'Amy',
  'Nicholas',
  'Angela',
  'Eric',
  'Shirley',
  'Jonathan',
  'Anna',
  'Stephen',
  'Brenda',
  'Larry',
  'Pamela',
  'Justin',
  'Emma',
  'Scott',
  'Nicole',
  'Brandon',
  'Helen',
  'Benjamin',
  'Samantha',
  'Samuel',
  'Katherine',
  'Raymond',
  'Christine',
  'Gregory',
  'Debra',
  'Alexander',
  'Rachel',
  'Patrick',
  'Carolyn',
  'Frank',
  'Janet',
  'Jack',
  'Catherine',
  'Dennis',
  'Maria',
  'Jerry',
  'Heather',
  'Tyler',
  'Diane',
  'Aaron',
  'Ruth',
  'Jose',
  'Julie',
  'Adam',
  'Olivia',
  'Nathan',
  'Joyce',
  'Henry',
  'Virginia',
  'Douglas',
  'Victoria',
  'Zachary',
  'Kelly',
  'Peter',
  'Lauren',
  'Kyle',
  'Christina',
  'Noah',
  'Joan',
  'Ethan',
  'Evelyn',
  'Jeremy',
  'Judith',
  'Walter',
  'Megan',
  'Christian',
  'Andrea',
  'Keith',
  'Cheryl',
  'Roger',
  'Hannah',
  'Terry',
  'Jacqueline',
  'Austin',
  'Martha',
  'Sean',
  'Gloria',
  'Gerald',
  'Teresa',
  'Carl',
  'Ann',
  'Harold',
  'Sara',
  'Dylan',
  'Madison',
  'Arthur',
  'Frances',
  'Lawrence',
  'Kathryn',
  'Jordan',
  'Janice',
  'Jesse',
  'Jean',
  'Bryan',
  'Abigail',
  'Billy',
  'Alice',
]

const lastNames = [
  'Smith',
  'Johnson',
  'Williams',
  'Brown',
  'Jones',
  'Garcia',
  'Miller',
  'Davis',
  'Rodriguez',
  'Martinez',
  'Hernandez',
  'Lopez',
  'Gonzalez',
  'Wilson',
  'Anderson',
  'Thomas',
  'Taylor',
  'Moore',
  'Jackson',
  'Martin',
  'Lee',
  'Perez',
  'Thompson',
  'White',
  'Harris',
  'Sanchez',
  'Clark',
  'Ramirez',
  'Lewis',
  'Robinson',
  'Walker',
  'Young',
  'Allen',
  'King',
  'Wright',
  'Scott',
  'Torres',
  'Nguyen',
  'Hill',
  'Flores',
  'Green',
  'Adams',
  'Nelson',
  'Baker',
  'Hall',
  'Rivera',
  'Campbell',
  'Mitchell',
  'Carter',
  'Roberts',
  'Gomez',
  'Phillips',
  'Evans',
  'Turner',
  'Diaz',
  'Parker',
  'Cruz',
  'Edwards',
  'Collins',
  'Reyes',
  'Stewart',
  'Morris',
  'Morales',
  'Murphy',
  'Cook',
  'Rogers',
  'Gutierrez',
  'Ortiz',
  'Morgan',
  'Cooper',
  'Peterson',
  'Bailey',
  'Reed',
  'Kelly',
  'Howard',
  'Ramos',
  'Kim',
  'Cox',
  'Ward',
  'Richardson',
  'Watson',
  'Brooks',
  'Chavez',
  'Wood',
  'James',
  'Bennett',
  'Gray',
  'Mendoza',
  'Ruiz',
  'Hughes',
  'Price',
  'Alvarez',
  'Castillo',
  'Sanders',
  'Patel',
  'Myers',
  'Long',
  'Ross',
  'Foster',
  'Jimenez',
  'Powell',
  'Jenkins',
  'Perry',
  'Russell',
  'Sullivan',
  'Bell',
  'Coleman',
  'Butler',
  'Henderson',
  'Barnes',
  'Gonzales',
  'Fisher',
  'Vasquez',
  'Simmons',
  'Romero',
  'Jordan',
  'Patterson',
  'Alexander',
  'Hamilton',
  'Graham',
  'Reynolds',
  'Griffin',
  'Wallace',
  'Moreno',
  'West',
  'Cole',
  'Hayes',
  'Bryant',
  'Herrera',
  'Gibson',
  'Ellis',
  'Tran',
  'Medina',
  'Aguilar',
  'Stevens',
  'Murray',
  'Ford',
  'Castro',
  'Marshall',
  'Owens',
  'Harrison',
  'Fernandez',
  'McDonald',
  'Woods',
  'Washington',
  'Kennedy',
  'Wells',
  'Vargas',
  'Henry',
  'Chen',
  'Freeman',
  'Webb',
  'Tucker',
  'Guzman',
  'Burns',
  'Crawford',
  'Olson',
  'Simpson',
  'Porter',
  'Hunter',
]

const companies = [
  'TechCorp',
  'InnovateLabs',
  'Global Solutions',
  'NextGen Systems',
  'Digital Dynamics',
  'Quantum Technologies',
  'Synergy Group',
  'Apex Innovations',
  'Stellar Enterprises',
  'Fusion Analytics',
  'Velocity Software',
  'Paramount Consulting',
  'Horizon Industries',
  'Catalyst Partners',
  'Pinnacle Corp',
  'Nexus Solutions',
  'Zenith Technologies',
  'Vertex Systems',
  'Acme Corporation',
  'Atlas Group',
  'Omega Industries',
  'Phoenix Technologies',
  'Prime Solutions',
  'Summit Enterprises',
  'Titan Corp',
  'Unity Systems',
  'Vanguard Group',
  'Beacon Technologies',
  'Cascade Solutions',
  'Delta Innovations',
  'Eclipse Systems',
  'Frontier Corp',
  'Gateway Technologies',
  'Helix Solutions',
  'Impact Enterprises',
  'Keystone Group',
  'Lighthouse Technologies',
  'Meridian Systems',
  'Nova Solutions',
  'Orbit Corp',
  'Prism Technologies',
  'Quest Solutions',
  'Radius Group',
  'Spectrum Enterprises',
  'Trident Systems',
]

const jobTitles = [
  'Software Engineer',
  'Senior Developer',
  'Product Manager',
  'Data Analyst',
  'Marketing Manager',
  'Sales Director',
  'HR Manager',
  'Financial Analyst',
  'Operations Manager',
  'UX Designer',
  'Project Manager',
  'Business Analyst',
  'Account Executive',
  'Customer Success Manager',
  'DevOps Engineer',
  'Chief Technology Officer',
  'Vice President',
  'Director of Engineering',
  'Marketing Coordinator',
  'Sales Representative',
  'Quality Assurance Engineer',
  'Technical Lead',
  'Scrum Master',
  'Product Owner',
  'Data Scientist',
  'Frontend Developer',
  'Backend Developer',
  'Full Stack Developer',
  'Systems Administrator',
  'Network Engineer',
  'Security Analyst',
  'Content Manager',
  'SEO Specialist',
  'Social Media Manager',
  'Graphic Designer',
  'Accountant',
  'Consultant',
  'Architect',
  'Team Lead',
  'Support Engineer',
]

const departments = [
  'Engineering',
  'Sales',
  'Marketing',
  'Human Resources',
  'Finance',
  'Operations',
  'Customer Success',
  'Product',
  'IT',
  'Legal',
  'Research and Development',
  'Quality Assurance',
  'Business Development',
  'Support',
  'Administration',
]

const cities = [
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Austin',
  'Jacksonville',
  'Fort Worth',
  'Columbus',
  'San Francisco',
  'Charlotte',
  'Indianapolis',
  'Seattle',
  'Denver',
  'Washington',
  'Boston',
  'Nashville',
  'Detroit',
  'Portland',
  'Las Vegas',
  'Memphis',
  'Louisville',
  'Baltimore',
  'Milwaukee',
  'Albuquerque',
  'Tucson',
  'Fresno',
  'Mesa',
  'Sacramento',
  'Atlanta',
  'Kansas City',
  'Colorado Springs',
  'Miami',
  'Raleigh',
  'Omaha',
  'Long Beach',
  'Virginia Beach',
  'Oakland',
  'Minneapolis',
  'Tampa',
]

const states = [
  'NY',
  'CA',
  'IL',
  'TX',
  'AZ',
  'PA',
  'TX',
  'CA',
  'TX',
  'CA',
  'TX',
  'FL',
  'TX',
  'OH',
  'CA',
  'NC',
  'IN',
  'WA',
  'CO',
  'DC',
  'MA',
  'TN',
  'MI',
  'OR',
  'NV',
  'TN',
  'KY',
  'MD',
  'WI',
  'NM',
  'AZ',
  'CA',
  'AZ',
  'CA',
  'GA',
  'MO',
  'CO',
  'FL',
  'NC',
  'NE',
  'CA',
  'VA',
  'CA',
  'MN',
  'FL',
]

const streetSuffixes = ['St', 'Ave', 'Blvd', 'Ln', 'Dr', 'Ct', 'Way', 'Rd', 'Pl', 'Ter']
const streetNames = [
  'Main',
  'Oak',
  'Maple',
  'Cedar',
  'Elm',
  'Washington',
  'Lake',
  'Hill',
  'Park',
  'River',
  'Pine',
  'Church',
  'Spring',
  'Forest',
  'Broadway',
  'Market',
]

// Utility functions
function randomItem<T>(array: Array<T>): T {
  return array[Math.floor(Math.random() * array.length)]
}

function randomBool(probability = 0.5): boolean {
  return Math.random() < probability
}

function generateEmail(firstName: string, lastName: string | null): string {
  const domains = ['gmail.com', 'yahoo.com', 'hotmail.com', 'outlook.com', 'company.com']
  const last = lastName || ''
  return `${firstName.toLowerCase()}.${last.toLowerCase()}@${randomItem(domains)}`
}

function generatePhone(): string {
  const areaCode = Math.floor(Math.random() * 900) + 100
  const prefix = Math.floor(Math.random() * 900) + 100
  const lineNumber = Math.floor(Math.random() * 9000) + 1000
  return `(${areaCode}) ${prefix}-${lineNumber}`
}

function generateStreetAddress(): string {
  const number = Math.floor(Math.random() * 9999) + 1
  return `${number} ${randomItem(streetNames)} ${randomItem(streetSuffixes)}`
}

function generatePostalCode(): string {
  return String(Math.floor(Math.random() * 90000) + 10000)
}

async function seedContacts() {
  console.log('🌱 Seeding contacts...')

  // For this seed, we'll use a fixed userId. In a real scenario, you'd want to:
  // 1. Query existing users from the database
  // 2. Distribute contacts across multiple users
  // For now, using a placeholder UUID

  const userId = 'KHxzt1HBTGEhtt770pI0VffWRHmTd7RT'

  const contacts = []
  const batchSize = 500 // Insert in batches for better performance

  for (let i = 0; i < 3000; i++) {
    const firstName = randomItem(firstNames)
    const lastName = randomBool(0.95) ? randomItem(lastNames) : null
    const hasCompany = randomBool(0.7)

    contacts.push({
      id: uuidv7(),
      userId,
      firstName,
      lastName,
      displayName: lastName ? `${firstName} ${lastName}` : firstName,
      nickname: randomBool(0.15) ? firstName.substring(0, 3) : null,
      primaryEmail: randomBool(0.9) ? generateEmail(firstName, lastName) : null,
      primaryPhone: randomBool(0.85) ? generatePhone() : null,
      company: hasCompany ? randomItem(companies) : null,
      jobTitle: hasCompany && randomBool(0.8) ? randomItem(jobTitles) : null,
      department: hasCompany && randomBool(0.6) ? randomItem(departments) : null,
      street: randomBool(0.5) ? generateStreetAddress() : null,
      city: randomBool(0.5) ? randomItem(cities) : null,
      state: randomBool(0.5) ? randomItem(states) : null,
      postalCode: randomBool(0.5) ? generatePostalCode() : null,
      country: randomBool(0.5) ? 'USA' : null,
      notes: randomBool(0.2) ? 'Met at conference. Follow up next quarter.' : null,
      website: randomBool(0.15)
        ? `https://www.${firstName.toLowerCase()}${lastName?.toLowerCase() || ''}.com`
        : null,
      isFavorite: randomBool(0.1),
    })

    // Insert in batches
    if (contacts.length === batchSize) {
      await db.insert(contact).values(contacts)
      console.log(`✓ Inserted ${i + 1} contacts...`)
      contacts.length = 0 // Clear the array
    }
  }

  // Insert any remaining contacts
  if (contacts.length > 0) {
    await db.insert(contact).values(contacts)
  }

  console.log('✅ Successfully seeded 3,000 contacts!')
}

// Run the seed function
seedContacts()
  .catch((error) => {
    console.error('❌ Error seeding contacts:', error)
    process.exit(1)
  })
  .finally(() => {
    process.exit(0)
  })
