/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as DashboardContactsIndexRouteImport } from './routes/dashboard/contacts.index'
import { Route as DashboardContactsNewRouteImport } from './routes/dashboard/contacts.new'
import { Route as DashboardContactsContactIdRouteImport } from './routes/dashboard/contacts.$contactId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as DashboardContactsContactIdEditRouteImport } from './routes/dashboard/contacts.$contactId.edit'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardContactsIndexRoute = DashboardContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContactsNewRoute = DashboardContactsNewRouteImport.update({
  id: '/contacts/new',
  path: '/contacts/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContactsContactIdRoute = DashboardContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardContactsContactIdEditRoute = DashboardContactsContactIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DashboardContactsContactIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof PublicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/contacts/$contactId': typeof DashboardContactsContactIdRouteWithChildren
  '/dashboard/contacts/new': typeof DashboardContactsNewRoute
  '/dashboard/contacts': typeof DashboardContactsIndexRoute
  '/dashboard/contacts/$contactId/edit': typeof DashboardContactsContactIdEditRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/contacts/$contactId': typeof DashboardContactsContactIdRouteWithChildren
  '/dashboard/contacts/new': typeof DashboardContactsNewRoute
  '/dashboard/contacts': typeof DashboardContactsIndexRoute
  '/dashboard/contacts/$contactId/edit': typeof DashboardContactsContactIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_public/': typeof PublicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/contacts/$contactId': typeof DashboardContactsContactIdRouteWithChildren
  '/dashboard/contacts/new': typeof DashboardContactsNewRoute
  '/dashboard/contacts/': typeof DashboardContactsIndexRoute
  '/dashboard/contacts/$contactId/edit': typeof DashboardContactsContactIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/contacts/$contactId'
    | '/dashboard/contacts/new'
    | '/dashboard/contacts'
    | '/dashboard/contacts/$contactId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/contacts/$contactId'
    | '/dashboard/contacts/new'
    | '/dashboard/contacts'
    | '/dashboard/contacts/$contactId/edit'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/dashboard'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_public/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/contacts/$contactId'
    | '/dashboard/contacts/new'
    | '/dashboard/contacts/'
    | '/dashboard/contacts/$contactId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/contacts/': {
      id: '/dashboard/contacts/'
      path: '/contacts'
      fullPath: '/dashboard/contacts'
      preLoaderRoute: typeof DashboardContactsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/contacts/new': {
      id: '/dashboard/contacts/new'
      path: '/contacts/new'
      fullPath: '/dashboard/contacts/new'
      preLoaderRoute: typeof DashboardContactsNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/contacts/$contactId': {
      id: '/dashboard/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/dashboard/contacts/$contactId'
      preLoaderRoute: typeof DashboardContactsContactIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/contacts/$contactId/edit': {
      id: '/dashboard/contacts/$contactId/edit'
      path: '/edit'
      fullPath: '/dashboard/contacts/$contactId/edit'
      preLoaderRoute: typeof DashboardContactsContactIdEditRouteImport
      parentRoute: typeof DashboardContactsContactIdRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(AuthRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(PublicRouteRouteChildren)

interface DashboardContactsContactIdRouteChildren {
  DashboardContactsContactIdEditRoute: typeof DashboardContactsContactIdEditRoute
}

const DashboardContactsContactIdRouteChildren: DashboardContactsContactIdRouteChildren = {
  DashboardContactsContactIdEditRoute: DashboardContactsContactIdEditRoute,
}

const DashboardContactsContactIdRouteWithChildren =
  DashboardContactsContactIdRoute._addFileChildren(DashboardContactsContactIdRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardContactsContactIdRoute: typeof DashboardContactsContactIdRouteWithChildren
  DashboardContactsNewRoute: typeof DashboardContactsNewRoute
  DashboardContactsIndexRoute: typeof DashboardContactsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardContactsContactIdRoute: DashboardContactsContactIdRouteWithChildren,
  DashboardContactsNewRoute: DashboardContactsNewRoute,
  DashboardContactsIndexRoute: DashboardContactsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
